#!/bin/bash

json_input=$(cat)  # Read JSON input from stdin
# {
#     "source": {
#       "bucket": "mybucket",
#       "versioned_file": "path/to/myobject", 
#       "debug": true,
#       "initial_version": "some_invented_generic_initial_version"      
#     },
#     "version": {
#         "ref": "61cbef"
#     }
# }

if [ "$debug" = true ] ; then
    >&2 echo "Check..."
    >&2 cat $json_input
fi

export bucket=$(echo $json_input | jq -r .source.bucket )
export versioned_file=$(echo $json_input | jq -r .source.versioned_file )
export debug=$(echo $json_input | jq -r .source.debug )
export initial_version=$(echo $json_input | jq -r .source.initial_version )
export version=$(echo $json_input | jq -r .version.ref )


gs_url="gs://${bucket}/${versioned_file}"

if [ -n "${version}" ]; then
    gs_url="${gs_url}#${version}"
fi

if gcloud storage objects describe "${gs_url}" > object_metadata.yml; then
    if [ -n "${initial_version}"]; then
      >&2 echo "Failed to retrieve object. Falling back to initial_version"
      current_version=$initial_version
    else
      >&2 echo "Failed to retrieve object and there is no initial version specified in source"
      exit 1
    fi
else
    current_version=$(cat object_metadata.yml | yq .generation)
fi

## And we will output...
# The list with all versions after 62cbef
# 
# [
#   { "ref": "61cbef" },
#   { "ref": "d74e01" },
#   { "ref": "7154fe" }
# ]
#
# Or alternatively return just the latest (not the best solution because it doesn't allow pinning)
# 
##
echo "[ { \"ref\": \"${current_version}\" } ]"