#!/bin/bash
set -e
source "$(dirname "$0")/functions.sh"

export directory=$1

json_input=$(cat)  # Read JSON input from stdin
# {
#     "source": {
#       "bucket": "mybucket",
#       "versioned_file": "myobject",
#       "debug": true,          
#     },
#    "params": {
#       "file": "path/to/my_local_file.txt"
#     }
# }

>&2 echo "Put..."

export debug=$(echo $json_input | jq -r .source.debug )

if [ "${debug}" = true ] ; then
    >&2 echo $json_input
fi

validate_inputs "$json_input" || exit 1

export bucket=$(echo $json_input | jq -r .source.bucket )
export versioned_file=$(echo $json_input | jq -r .source.versioned_file )
export file=$(echo $json_input | jq -r .params.file )

if [ "${debug}" = true ] ; then
  >&2 echo "/opt/resource/gcs upload \"$directory/$file\" \"gs://${bucket}/${versioned_file}\""
fi

/opt/resource/gcs upload "$directory/$file" "gs://${bucket}/${versioned_file}"

if [[ "${versioned_file}" == */ ]]; then
  >&2 echo "Put directory."
  
  output_string="{ \"version\": { \"ref\": \"SKIP_DOWNLOAD\" }}"

  if [ "${debug}" = true ] ; then
    >&2 echo $output_string
  fi

  echo $output_string
  exit 0
fi

if /opt/resource/gcs describe "gs://${bucket}/${versioned_file}" > object_metadata.json; then
  current_version=$(jq -r .generation object_metadata.json)
  creation_time=$(jq -r .creation_time object_metadata.json)
  update_time=$(jq -r .update_time object_metadata.json)
  md5_hash=$(jq -r .md5_hash object_metadata.json)
  metageneration=$(jq -r .metageneration object_metadata.json)
  storage_url=$(jq -r .storage_url object_metadata.json)
  size=$(jq -r .size object_metadata.json)
else
  >&2 echo "Failed to describe uploaded object"
  exit 1
fi

# {
#   "version": { "ref": "61cebf" },
#   "metadata": [
#     { "name": "commit", "value": "61cebf" },
#     { "name": "author", "value": "Mick Foley" }
#   ]
# }

output_string="{
  \"version\": { \"ref\": \"${current_version}\" },
  \"metadata\": [
    { \"name\": \"generation\", \"value\": \"${current_version}\"}, \
    { \"name\": \"creation_time\", \"value\": \"${creation_time}\"}, \
    { \"name\": \"update_time\", \"value\": \"${update_time}\"}, \
    { \"name\": \"md5_hash\", \"value\": \"${md5_hash}\"}, \
    { \"name\": \"metageneration\", \"value\": \"${metageneration}\"}, \
    { \"name\": \"storage_url\", \"value\": \"${storage_url}\"}, \
    { \"name\": \"size\", \"value\": \"${size}\"} \
  ]
}"

if [ "${debug}" = true ] ; then
    >&2 echo $output_string
fi
echo $output_string
